import { Options, Gradient, QrPartOptions } from "./types";

export type RandomizeConfig = {
  /** Randomize the main QR dots solid color (clears gradient) */
  dotsColor?: boolean;
  /** Randomize the main QR dots as a linear gradient (clears solid color) */
  dotsGradient?: boolean;
  /** Randomize the main QR dots shape */
  dotsShape?: boolean;
  /** Randomize inner eye (ball) solid color (clears gradient) */
  cornersDotColor?: boolean;
  /** Randomize inner eye (ball) as a linear gradient (clears solid color) */
  cornersDotGradient?: boolean;
  /** Randomize inner eye (ball) shape */
  cornersDotShape?: boolean;
  /** Randomize outer eye (frame) solid color (clears gradient) */
  cornersSquareColor?: boolean;
  /** Randomize outer eye (frame) as a linear gradient (clears solid color) */
  cornersSquareGradient?: boolean;
  /** Randomize outer eye (frame) shape */
  cornersSquareShape?: boolean;
  /** Randomize background solid color (clears gradient) */
  backgroundColor?: boolean;
  /** Randomize background as a linear gradient (clears solid color) */
  backgroundGradient?: boolean;
  /** Randomize border radius (0–100) */
  borderRadius?: boolean;
};

function mulberry32(seed: number): () => number {
  let s = seed >>> 0 || 1;
  return function () {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function pick<T>(arr: readonly T[], rng: () => number): T {
  return arr[Math.floor(rng() * arr.length)];
}

function hslToHex(h: number, s: number, l: number): string {
  const sl = s / 100;
  const ll = l / 100;
  const a = sl * Math.min(ll, 1 - ll);
  const f = (n: number) => {
    const k = (n + h / 30) % 12;
    const c = ll - a * Math.max(Math.min(k - 3, 9 - k, 1), -1);
    return Math.round(255 * c)
      .toString(16)
      .padStart(2, "0");
  };
  return `#${f(0)}${f(8)}${f(4)}`;
}

/**
 * Dark saturated color for QR dots / eyes.
 * Lightness 8–15 % guarantees WCAG contrast ≥ 7:1 against any light background
 * produced by randomLightColor, even for high-luminance hues like green/yellow.
 */
function randomDarkColor(rng: () => number): string {
  const h = Math.floor(rng() * 360);
  const s = 60 + Math.floor(rng() * 40); // 60–100 %
  const l = 8 + Math.floor(rng() * 8);   // 8–15 %
  return hslToHex(h, s, l);
}

/**
 * Light desaturated color for the QR background.
 * Lightness 85–97 %, low saturation — always provides enough contrast
 * against the dark dot/eye colors generated by randomDarkColor.
 */
function randomLightColor(rng: () => number): string {
  const h = Math.floor(rng() * 360);
  const s = Math.floor(rng() * 25);       // 0–25 %
  const l = 85 + Math.floor(rng() * 13); // 85–97 %
  return hslToHex(h, s, l);
}

function randomDarkGradient(rng: () => number): Gradient {
  return {
    type: "linear",
    rotation: Math.floor(rng() * 360),
    colorStops: [
      { offset: "0%", color: randomDarkColor(rng) },
      { offset: "100%", color: randomDarkColor(rng) },
    ],
  };
}

function randomLightGradient(rng: () => number): Gradient {
  return {
    type: "linear",
    rotation: Math.floor(rng() * 360),
    colorStops: [
      { offset: "0%", color: randomLightColor(rng) },
      { offset: "100%", color: randomLightColor(rng) },
    ],
  };
}

const DOT_ICON_SHAPES = [
  "dots-square",
  "dots-rounded",
  "dots-classy",
  "dots-classy-rounded",
  "dots-extra-rounded",
] as const;

const DOT_FIGURE_SHAPES = [
  "square",
  "dots",
  "extra-rounded",
  "rounded",
  "classy",
  "classy-rounded",
] as const;

const INNER_EYE_SHAPES = [
  "inner-eye-square",
  "inner-eye-dot",
  "inner-eye-dots",
  "inner-eye-rounded",
  "inner-eye-classy",
  "inner-eye-extra-rounded",
  "inner-eye-extra-classy",
  "inner-eye-star",
] as const;

const OUTER_EYE_SHAPES = [
  "outer-eye-square",
  "outer-eye-dot",
  "outer-eye-dots",
  "outer-eye-rounded",
  "outer-eye-classy",
  "outer-eye-extra-rounded",
  "outer-eye-extra-classy",
  "outer-eye-heart",
  "outer-eye-star",
] as const;

/**
 * Returns a new `Options` object with selected fields replaced by random values.
 *
 * Color generation is contrast-aware by design: dot/eye colors are always dark
 * (L 8–15 %), background colors are always light (L 85–97 %). This guarantees
 * a WCAG contrast ratio ≥ 7:1 so the result is always scannable without any
 * validation loop.
 *
 * @param base   — Starting options; untouched fields are preserved as-is.
 * @param config — Flags that control which fields are randomised.
 * @param seed   — Optional integer seed for reproducible results.
 *                 When omitted, a random seed based on `Date.now()` is used.
 */
export function randomizeOptions(
  base: Options,
  config: RandomizeConfig,
  seed?: number,
): Options {
  const rng = mulberry32(seed ?? (Date.now() & 0xffffffff));
  const result: Options = { ...base };

  // --- dots ---
  if (config.dotsColor || config.dotsGradient || config.dotsShape) {
    result.dotsOptions = { ...base.dotsOptions };
    if (config.dotsGradient) {
      result.dotsOptions.gradient = randomDarkGradient(rng);
      result.dotsOptions.color = undefined;
    } else if (config.dotsColor) {
      result.dotsOptions.color = randomDarkColor(rng);
      result.dotsOptions.gradient = undefined;
    }
    if (config.dotsShape) {
      result.dotsOptions.shape =
        rng() > 0.5
          ? { type: "icon", path: pick(DOT_ICON_SHAPES, rng) }
          : { type: "figure", path: pick(DOT_FIGURE_SHAPES, rng) };
    }
  }

  // --- inner eye (cornersDot) ---
  if (config.cornersDotColor || config.cornersDotGradient || config.cornersDotShape) {
    result.cornersDotOptions = { ...base.cornersDotOptions };
    if (config.cornersDotGradient) {
      result.cornersDotOptions.gradient = randomDarkGradient(rng);
      result.cornersDotOptions.color = undefined;
    } else if (config.cornersDotColor) {
      result.cornersDotOptions.color = randomDarkColor(rng);
      result.cornersDotOptions.gradient = undefined;
    }
    if (config.cornersDotShape) {
      result.cornersDotOptions.shape = {
        type: "icon",
        path: pick(INNER_EYE_SHAPES, rng),
      };
    }
  }

  // --- outer eye (cornersSquare) ---
  if (config.cornersSquareColor || config.cornersSquareGradient || config.cornersSquareShape) {
    result.cornersSquareOptions = { ...base.cornersSquareOptions };
    if (config.cornersSquareGradient) {
      result.cornersSquareOptions.gradient = randomDarkGradient(rng);
      result.cornersSquareOptions.color = undefined;
    } else if (config.cornersSquareColor) {
      result.cornersSquareOptions.color = randomDarkColor(rng);
      result.cornersSquareOptions.gradient = undefined;
    }
    if (config.cornersSquareShape) {
      result.cornersSquareOptions.shape = {
        type: "icon",
        path: pick(OUTER_EYE_SHAPES, rng),
      };
    }
  }

  // --- background ---
  if (config.backgroundColor || config.backgroundGradient) {
    result.backgroundOptions = { ...base.backgroundOptions };
    if (config.backgroundGradient) {
      result.backgroundOptions.gradient = randomLightGradient(rng);
      result.backgroundOptions.color = undefined;
    } else if (config.backgroundColor) {
      result.backgroundOptions.color = randomLightColor(rng);
      result.backgroundOptions.gradient = undefined;
    }
  }

  // --- borderRadius ---
  if (config.borderRadius) {
    result.borderRadius = Math.floor(rng() * 101); // 0–100
  }

  return result;
}

// ─── invertOptions ────────────────────────────────────────────────────────────

function invertHex(color: string): string {
  if (!color.startsWith("#") || color.length < 7) return color;
  const n = parseInt(color.slice(1, 7), 16);
  return "#" + (0xffffff ^ n).toString(16).padStart(6, "0");
}

function invertGradient(g: Gradient): Gradient {
  return {
    ...g,
    colorStops: g.colorStops.map((s) => ({ ...s, color: invertHex(s.color) })),
  };
}

function invertPart(part: QrPartOptions | undefined): QrPartOptions | undefined {
  if (!part) return part;
  return {
    ...part,
    color: part.color !== undefined ? invertHex(part.color) : undefined,
    gradient: part.gradient !== undefined ? invertGradient(part.gradient) : undefined,
  };
}

/**
 * Returns a new `Options` object with every colour mathematically inverted
 * (each channel: 255 − value). Swaps dark dots ↔ light background, turning a
 * standard QR into an inverted one and vice-versa.
 */
export function invertOptions(options: Options): Options {
  const result: Options = { ...options };

  result.dotsOptions = invertPart(options.dotsOptions);
  result.cornersDotOptions = invertPart(options.cornersDotOptions);
  result.cornersSquareOptions = invertPart(options.cornersSquareOptions);

  if (options.backgroundOptions) {
    result.backgroundOptions = {
      ...options.backgroundOptions,
      color:
        options.backgroundOptions.color !== undefined
          ? invertHex(options.backgroundOptions.color)
          : undefined,
      gradient:
        options.backgroundOptions.gradient !== undefined
          ? invertGradient(options.backgroundOptions.gradient)
          : undefined,
    };
  }

  return result;
}
